### ISSUE TITLE
Release workflow error

### ISSUE THREAD

**Issue by Deuchnord** [Kosmorro/kosmorro#136]
The release workflow fails with the following error:

```
if [ "$POEDITOR_API_ACCESS" != "" ]; then \
        python3 .scripts/build/getlangs.py; \
        python3 setup.py compile_catalog; \
fi
Traceback (most recent call last):
  File ".scripts/build/getlangs.py", line 12, in <module>
    PROJECT_ID = os.environ['POEDITOR_PROJECT_ID']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'POEDITOR_PROJECT_ID'
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

Complete logs: https://gist.github.com/Deuchnord/f310919a0ec03a180e487b7163876a8b

**Comment by Deuchnord** [comment]
Fixed with #146
